### ISSUE TITLE
Scraping OpenPrescribing.net

### ISSUE THREAD

**Issue by evansd** [tmylk/yearly_prescriptions#1]
Hi, I work on OpenPrescribing.net and we think this is great! We're really pleased to see people building off and expanding on our work like this.

Just one question on this: _someone_ was scraping our API quite hard on 5, 6 and 7 March. In particular, lots of requests to URLs like:
```
/api/1.0/spending_by_org/?format=csv&org_type=practice&code=23350703834&org=00L
```

The load this was putting on our server starting impacting our other users so we ended up having to block these requests. We put a message in the error response asking the originator to get in touch, but I don't know if this will have been read.

Could these requests have been from you? If so, you should be aware that you'll only have a partial scrape as we blocked the requests part way thorough.

We're very happy to have this data shared and re-used (it's not ours, after all) but if you need a bulk download like this there are more efficient ways to do it than scraping the API so get in touch and we'll see what we can do.

Also, if it wasn't you making those specific requests above then you can ignore this — none of the other traffic we were getting was causing any issues.

Thanks!

Dave

**Comment by tmylk** [comment]
Hi. Thanks for reaching out but it wasn't me. I download the primary from [NHSBSA](https://github.com/tmylk/yearly_prescriptions/blob/main/prescriptions.py#L85)
